backend:
  name: github
  repo: johnnyelwailer/hempbar # Path to your Github repository
  branch: master # Branch to update
media_folder: "images/uploads"
collections:
  - name: "pages"
    label: "Pages"
    folder: "pages"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}